changelog:
  exclude:
    labels:
      - documentation
      - chore
      - ci
      - style
    authors:
      - dependabot
      - dependabot[bot]
  categories:
    - title: "🚀 Features"
      labels:
        - enhancement
        - feature
    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - fix
    - title: "📦 Other"
      labels:
        - "*"
